# Generated by Django 5.2.5 on 2025-08-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IntentoRendir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento_num', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('mesa', models.CharField(choices=[('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('MAYO', 'Mayo'), ('JULIO', 'Julio'), ('SEPTIEMBRE', 'Septiembre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], max_length=15)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='gestionMaterias.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Correlativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'D'), ('F', 'F')], max_length=1)),
                ('correlativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_para', to='gestionMaterias.materia')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_de', to='gestionMaterias.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('APROBADA', 'Aprobada'), ('APROBADA LIBRE', 'Aprobada Libre'), ('PROMOCION', 'Promoción'), ('REGULAR', 'Regular'), ('INSCRIPTO', 'Inscripto'), ('NO_INSCRITO', 'No Inscripto')], max_length=15)),
                ('tipo', models.CharField(choices=[('ANUAL', 'Anual'), ('CUATRIMESTRAL', 'Cuatrimestral')], max_length=15)),
                ('ausencias', models.IntegerField(default=0)),
                ('nota_final', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='gestionMaterias.materia')),
            ],
        ),
    ]
